name: workflow with multiple stages

on: push

jobs:
  job-on-unbuntu:
    runs-on: unbuntu-latest
    steps:
    -  run: date
    -  run: pwd

  job-on-windows:
      name: A job running on windows
      runs-on: windows-latest
      steps:
        - name: first step in windows job
          run: date
        - run: ls -la
  dependent-job-1: 
    needs: [job-on-unbuntu, job-on-windows]
    runs-on: mac-latest
    name: a job that runs on mac after first two jobs
    steps:
      - run: pwd
      - name: new step
        run: ls
      - run: env
  dependent-job-2:
    needs: dependent-job-1
    runs-on: unbuntu-latest
    name: a final job
    steps:
      - run: echo wow this is so cool!
  
